server:
  host: localhost
  port: 8080
postgres:
  host: localhost
  port: 5432
  user: crud
  password: ${POSTGRES_PASSWORD}
  db: crud
  sslmode: disable
redis:
  host: localhost
  port: 6379
session:
  ttl: "12h"